services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dachi
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: springdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
